name: pansearch
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - argtable2=2.13
  - bedtools=2.31.0
  - biopython=1.81
  - blast=2.14.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.5.7
  - clustalo=1.2.4
  - curl=8.1.2
  - entrez-direct=16.2
  - gettext=0.21.1
  - hmmer=3.3.2
  - keyutils=1.6.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.1.2
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libgomp=13.1.0
  - libidn2=2.3.4
  - liblapack=3.9.0
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libopenblas=0.3.23
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.1.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libzlib=1.2.13
  - ncurses=6.4
  - numpy=1.25.0
  - openssl=3.1.1
  - pandas=2.0.3
  - pcre=8.45
  - perl=5.32.1
  - perl-archive-tar=2.40
  - perl-carp=1.38
  - perl-common-sense=3.75
  - perl-compress-raw-bzip2=2.201
  - perl-compress-raw-zlib=2.105
  - perl-encode=3.19
  - perl-exporter=5.72
  - perl-exporter-tiny=1.002002
  - perl-extutils-makemaker=7.70
  - perl-io-compress=2.201
  - perl-io-zlib=1.14
  - perl-json=4.10
  - perl-json-xs=2.34
  - perl-list-moreutils=0.430
  - perl-list-moreutils-xs=0.430
  - perl-parent=0.236
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.62
  - perl-types-serialiser=1.01
  - pip=23.1.2
  - python=3.11.4
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3
  - readline=8.2
  - setuptools=68.0.0
  - six=1.16.0
  - tk=8.6.12
  - tzdata=2023c
  - wget=1.20.3
  - wheel=0.40.0
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2
